
# Domain for dnsserver IEPEE service.
# You should set NS record as this dnsserver
DOMAIN: iep.ee

DOMAIN_IP: 3.34.113.218

DEFAULT_IPV4:
DEFAULT_IPV16:

DNS_PORT: 53

SOA:
  MNAME: ns.iep.ee
  RNAME: me.billo.io
  SERIAL: 2021042300
  REFRESH:
  RETRY:
  EXPIRE:
  MINIMUM:
  VALUE:

NSS:
  - ns1.iep.ee: 3.34.113.218
  - ns2.iep.ee: 3.34.113.218

WEB_PORT:
